### ISSUE TITLE
Is there a way to auto excute command?

### ISSUE THREAD

**Issue by nick-ChenZe** [AdrianWilczynski/TerminalCommandShortcuts#15]
Hi, i'm using this extension, what confused me is when i typed execute command. it only invoke the terminal, and send text to it, not excute it, how can i config?

**Comment by medopaw** [comment]
Adding `"auto": true` to the config should do it.

**Comment by nick-ChenZe** [comment]
> Adding `"auto": true` to the config should do it.

Thanks a lot, that works
