### ISSUE TITLE
Add UI option to configure the commands

### ISSUE THREAD

**Issue by glowinthedark** [AdrianWilczynski/TerminalCommandShortcuts#5]
There does not seem to be a way to edit the commands, or at least the documentation dos not mention how to open the config.

**Comment by Grrrrrrrrrrrrrrrr** [comment]
I think this part of the [README.md](https://github.com/AdrianWilczynski/RunTerminalCommand/blob/master/README.md) might help you open the config:

> How to edit your command list:
> VSCode -> File -> Preferences -> Settings
> 
> It will show the list: [Text Editor, Workbench, Window, Features, Application, Extension].
> 
> Click on "Extensions", Scroll down and click on "Run Terminal Command" -> Edit in Settings.Json
> 
> Or just open and edit directly the file: C:\Users\{YOUR USERNAME}\AppData\Roaming\Code\User\Settings.Json
> 
> Now you can edit the commands you want

Or you can open the settings by searching for `Preferences: Open Settings (JSON)` in the command palette.
Then search the file for `runTerminalCommand.commands` and edit that.

**Comment by CalamitousCode** [comment]
I think this part of the [README.md](https://github.com/AdrianWilczynski/RunTerminalCommand/blob/master/README.md) might help you open the config:

> How to edit your command list:
> VSCode -> File -> Preferences -> Settings
> 
> It will show the list: [Text Editor, Workbench, Window, Features, Application, Extension].
> 
> Click on "Extensions", Scroll down and click on "Run Terminal Command" -> Edit in Settings.Json
> 
> Or just open and edit directly the file: C:\Users{YOUR USERNAME}\AppData\Roaming\Code\User\Settings.Json
> 
> Now you can edit the commands you want

Or you can open the settings by searching for `Preferences: Open Settings (JSON)` in the command palette.
Then search the file for `runTerminalCommand.commands` and edit that.

**Comment by glowinthedark** [comment]
@CalamitousCode: thanks and sorry for the noise!
